config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :labels
  resources :posts
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  get 'change_language/:language', to: 'application#change_language', as: :change_language

end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand navbar-dark flex-column flex-md-row bd-navbar" style="padding-left: 50px; padding-right:50px">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder='<%= t('common.search') %>' aria-label="Search">
      </form>
      <% if user_signed_in? %>
        <div class="ml-auto">
          <%= link_to "Perfil", edit_user_registration_path, class: "btn btn-prymary" %>
          <%= button_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
        </div>
      <% else %>
        <div class="ml-auto">
          <%= link_to t('common.sign_in'), new_user_session_path, class: "btn btn-success", style: "background-color: #133E99; border-color: #133E99;" %>
          <%= link_to t('common.sign_up'), new_user_registration_path, class: "btn btn-warning" %>
        </div>
      <% end %> 
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <% if I18n.locale == :es %>
              ES
            <% else %>
              ENG
            <% end %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><%= link_to "ENG", change_language_path('en'), class: 'dropdown-item' %></li>
            <li><%= link_to "ES", change_language_path('es'), class: 'dropdown-item' %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>